### PR TITLE
Add RBAC support

### PR DESCRIPTION
**Pull request by rfancn**
## Proposed Changes
Since kubernetes 1.6, RBAC was introduced and kubeadm enabled RBAC by default in the latest releases.
If RBAC is enabled and autocluster backend using k8s,  when autocluster try to find_best_node_to_join, it will access endpoints resource on kubernetes API server, if no corresponding role/rolebinding/serviceaccount exist at this time, the https request will be failed as below:
```
=INFO REPORT==== 14-Nov-2017::10:12:30 ===
autocluster: GET https://kubernetes.default.svc.cluster.local:443/api/v1/namespaces/default/endpoints/rabbitmq

=INFO REPORT==== 14-Nov-2017::10:12:30 ===
autocluster: Response: [{ok,{{"HTTP/1.1",403,"Forbidden"},
                             [{"date","Tue, 14 Nov 2017 10:12:30 GMT"},
                              {"content-length","93"},
                              {"content-type","text/plain"},
                              {"x-content-type-options","nosniff"}],
                             "User \"system:serviceaccount:default:default\" cannot get endpoints in the namespace \"default\"."}}]
```

Below files changed and added to suport RBAC:

- Created rabbitmq-rbac.yaml to setup new role/rolebinding/serviceaccount for rabbitmq
- Changed README.md(add instruction to apply rabbitmq-rbac.yaml)
- Add "serviceAccountName" in rabbitmq.yaml

## Types of Changes
- [ ] Bugfix (non-breaking change which fixes issue #NNNN)
- [ ] New feature (non-breaking change which adds functionality)
- [x ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, appearance)

## Checklist
- [ x] I have read the `CONTRIBUTING.md` document
- [ ] I have signed the CA (see https://cla.pivotal.io/sign/rabbitmq)
- [x ] All tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in related repositories

## Further Comments
N/A

### CODE REVIEW

**Comment by michaelklishin** [comment]
@rfancn may I ask you to take a look if this can be rebased/applied to the `stable` branch?

**Comment by rfancn** [comment]
Yes, it is fine to be rebased/applied for stable branch.

**Comment by rfancn** [comment]
@michaelklishin Yes, it is fine to be rebased/applied to stable branch.

**Comment by Gsantomaggio** [comment]
@michaelklishin @rfancn Can I suggest to create another example? instead of modifying this one? thanks

**Comment by rfancn** [comment]
@Gsantomaggio Yes, create another example would be better, for non-RBAC example, it doesn't need serviceAccountName in rabbitmq.yaml.

**Comment by michaelklishin** [comment]
@rfancn let's move to using a new example and basing it on the `stable` branch (and submitting a new PR against it). Thank you for your time!

**Comment by michaelklishin** [comment]
Superseded by #60.

**Pull request closed without merging**
