### PR TITLE
Add new example supporting RBAC

### PR DESCRIPTION
**Pull request by rfancn**
## Proposed Changes
Since kubernetes 1.6, RBAC was introduced and kubeadm enabled RBAC by default in the latest releases.
If RBAC is enabled and autocluster backend using k8s,  when autocluster try to find_best_node_to_join, it will access endpoints resource on kubernetes API server, if no corresponding role/rolebinding/serviceaccount exist at this time, the https request will be failed as below:
```
=INFO REPORT==== 14-Nov-2017::10:12:30 ===
autocluster: GET https://kubernetes.default.svc.cluster.local:443/api/v1/namespaces/default/endpoints/rabbitmq

=INFO REPORT==== 14-Nov-2017::10:12:30 ===
autocluster: Response: [{ok,{{"HTTP/1.1",403,"Forbidden"},
                             [{"date","Tue, 14 Nov 2017 10:12:30 GMT"},
                              {"content-length","93"},
                              {"content-type","text/plain"},
                              {"x-content-type-options","nosniff"}],
                             "User \"system:serviceaccount:default:default\" cannot get endpoints in the namespace \"default\"."}}]
```

Below files changed and added to suport RBAC when compared the examples/k8s_statefulsets:

- Created rabbitmq-rbac.yaml to setup new role/rolebinding/serviceaccount for rabbitmq
- Changed README.md(add instruction to apply rabbitmq-rbac.yaml)
- Add "serviceAccountName" in rabbitmq.yaml

## Types of Changes
- [ ] Bugfix (non-breaking change which fixes issue #NNNN)
- [ ] New feature (non-breaking change which adds functionality)
- [x ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, appearance)

## Checklist
- [ x] I have read the `CONTRIBUTING.md` document
- [ ] I have signed the CA (see https://cla.pivotal.io/sign/rabbitmq)
- [x ] All tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in related repositories

## Further Comments
N/A

### CODE REVIEW

**Comment by michaelklishin** [comment]
Again, can we rebase this on top of `stable` and submit against `stable`?

**Comment by rfancn** [comment]
@michaelklishin Yes

**Comment by rfancn** [comment]
@michaelklishin I don't know how to rebase it, for it reports error like below:

```
$ git remote -v
origin  https://github.com/rfancn/rabbitmq-autocluster.git (fetch)
origin  https://github.com/rfancn/rabbitmq-autocluster.git (push)
rabbitmq        https://github.com/rabbitmq/rabbitmq-autocluster (fetch)
rabbitmq        https://github.com/rabbitmq/rabbitmq-autocluster (push)

$ git pull --rebase rabbitmq stable
From https://github.com/rabbitmq/rabbitmq-autocluster
 * branch            stable     -> FETCH_HEAD
First, rewinding head to replay your work on top of it...
Applying: Change module for json functions
Using index info to reconstruct a base tree...
M       src/autocluster_consul.erl
M       src/autocluster_httpc.erl
M       test/src/autocluster_consul_tests.erl
M       test/src/autocluster_k8s_tests.erl
Falling back to patching base and 3-way merge...
Auto-merging test/src/autocluster_k8s_tests.erl
Auto-merging test/src/autocluster_consul_tests.erl
Auto-merging src/autocluster_httpc.erl
Auto-merging src/autocluster_consul.erl
CONFLICT (content): Merge conflict in src/autocluster_consul.erl
Failed to merge in the changes.
Patch failed at 0001 Change module for json functions
The copy of the patch that failed is found in:
   /home/ryan/rabbitmq-autocluster/.git/rebase-apply/patch

When you have resolved this problem, run "git rebase --continue".
If you prefer to skip this patch, run "git rebase --skip" instead.
To check out the original branch and stop rebasing, run "git rebase --abort".
```

**Comment by michaelklishin** [comment]
Thank you!

**Pull request merged**
