### PR TITLE
Add consul tag support

### PR DESCRIPTION
**Pull request by akissa**
Adds support for tags to enable use of consul configured load balancers such as fabio

### CODE REVIEW

**Review by michaelklishin — APPROVED** [review]

**Comment by michaelklishin** [comment]
@akissa thank you! Would you be interested in forward porting this to https://github.com/rabbitmq/rabbitmq-peer-discovery-consul/? I'm happy to do that if you wouldn't :)

**Comment by akissa** [comment]
@michaelklishin Thanks, i can look at the forward port but not much time at the moment. I will get some downtime in December if it is not yet done by then i will do it then.

**Comment by michaelklishin** [comment]
@akissa no worries, we'll do it.

**Comment by michaelklishin** [comment]
Oh, and a new autocluster release is coming in the next couple of days.

**Comment by akissa** [comment]
@michaelklishin Thanks

**Pull request merged**
